### ISSUE TITLE
Abstração de layer de database

### ISSUE THREAD

**Issue by andrepg** [MAPGSolutions/Delphi-SDK#1]
Métodos públicos propostos:

- `CriaConexao returns TSQLDataset`
- `RetornaConexao returns TSQLDataset`
- `FinalizaConexao returns TSQLDataset`

Estes métodos são responsáveis por gerenciar a conexão. O layer de database deve conter apenas o suficiente para prover um componente pronto de conexão ao sistema. 

Sempre que o programador solicitar um acesso ao banco será retornado um único `TSQLDataset` pelo método `RetornaConexao`. O programador deve ser encarregar de criar os ClientDataSets para manipulação de dados em cada uma das janelas que faz tratamento de dados, a nível de execução dentro do objeto do Formulário.

**Comment by andrepg** [comment]
@imozart 

Quanto aos parâmetros de conexão, alguma sugestão de em que ponto alimentar? Eles devem vir de um local configurado pelo usuário. No Laravel temos um arquivo .env pra definir variáveis de ambiente como conexão de banco de dados e driver. 

No final eu teria um arquivo .env similar a isso:

```yml
DB_USERNAME=usuariodobanco
DB_PASSWORD=senhadousuario
DB_DRIVER=[ mysql, pgsql, mssql, mariadb ]
DB_HOST=[ host.domain.tld, 0.0.0.0 ]
```

E na hora de rodar a aplicação eu pego esses valores com um `GetEnv( NomeDaVariavel )`. Poderíamos tentar desenvolver um array assim e usar uma função pra alimentar e retornar True ou False. 

No caso o objeto teria um método a mais que iria ler do array formado em tempo de execução na hora de rodar a aplicação. Tipo um INI.

**Comment by imozart** [comment]
Certo. A ideia é essa mesmo, abstrair o máximo possível para deixar com um baixo acoplamento. 
Acredito que iremos trabalhar com o FireDac não?

Sobre o arquivo de configuração: Podemos ter um arquivo criptografado que irá ter os dados de conexão que será lido ao abrir o sistema pela primeira vez e podemos manter esses dados na sessão do usuário (um conection salvo, uma lista, etc) onde iríamos recuperar os dados de início de sessão e a partir daí fazer tudo que precisa. 

Conseguimos sim fazer um SDK dessa forma. Talvez ter até um método que busque os dados do arquivo antes de executar alguma operação, creio que isso não deixará lento a aplicação. Serão poucos dados nesse arquivo.

**Comment by andrepg** [comment]
Seria FireDAC porque é nativo e já temos suporte aos bancos principais. mas construído de jeito que, se eu mudar o componente no CriaConexão nada vai mudar em diante. A gente só seta o tipo de conexão num Record e passa ele com parametro do GetConexao. Vou criar um SetParametrosConexao e um GetParametrosConexao pra encapsular

![image](https://user-images.githubusercontent.com/12430295/87739324-fadcbe00-c7b5-11ea-999b-cb83110caefa.png)

Algo mais ou menos igual na imagem. Já vou atribuir esse issue pra mim e começar a trabalhar nele.

**Comment by imozart** [comment]
Muito bom. Assim a abstração estará em baixo nível.

**Comment by andrepg** [comment]
@imozart Começou a ficar mais tenso do que eu esperava haha 

Acho que vou ter precisar de uma ajuda para dar uma refrescada na mente. Enquanto isso vou fazendo mais alterações no branch de refatoração e otimização de código que já existe. 

Quando puder, faz um `pull` e analisa o código do `gpSDK`, por favor. Ele contém  o _runner_ de teste e a BPL principal na qual eu estou trabalhando no momento. 

Acho que, pelo bem do minimalismo, esse componente que eu estou escrevendo deve ficar por conta só dessas manipulações que já estão planejadas (CRUD e validações). 

Mas não vai ser ele o repassado para a aplicação. Acho que precisamos de uma espécie de `ClientDataSet` personalizado em tempo de execução para trabalhar com as requisições. Algo assim. Estou começando a achar complexo colocar tudo num balaio só. 

> Talvez até renomear e repensar um pouco a arquitetura antes de abrir o PR. É nisso que preciso de sua ajuda.

[Olha o branch aqui depois ;)](https://github.com/MAPGSolutions/Delphi-SDK/tree/features/novo-objeto-conexao)

**Comment by andrepg** [comment]
Estou fechando esse issue porque o componente de conexão foi incluído, nas atuais estruturas e, com a nova implementação do SQL Builder podemos mesclar as funcionalidades e trabalhar de outra forma.
